apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: classify-deployment
spec:
  maxReplicas: 8
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 80
        type: Utilization
    type: Resource
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: classify-deployment