name: fluttermeow
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  geolocator: ^11.0.0
  google_fonts: ^6.1.0
  google_maps_flutter: ^2.0.3
  intl: ^0.19.0
  location: ^5.0.0
  path_provider: ^2.0.1
  sqflite: ^2.0.0+3
  stop_watch_timer: ^3.1.1

  path: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
