apiVersion: apps/v1
kind: Deployment
metadata:
  name: activity-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: plog-activity
  template:
    metadata:
      labels:
        app: plog-activity
    spec:
      containers:
        - name: plog-activity
          image: skyish/plog-activity:latest
          envFrom:
            - configMapRef:
                name: deployment-configmap
            - secretRef:
                name: deployment-secret
          ports:
            - containerPort: 5002

---
apiVersion: v1
kind: Service
metadata:
  name: plog-activity-service
spec:
  selector:
    app: plog-activity
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
