apiVersion: apps/v1
kind: Deployment
metadata:
  name: classify-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: plog-classify
  template:
    metadata:
      labels:
        app: plog-classify
    spec:
      containers:
        - name: plog-classify
          image: skyish/plog-classify:latest
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: plog-classify-service
spec:
  type: LoadBalancer
  selector:
    app: plog-classify
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
