apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: plog-user
  template:
    metadata:
      labels:
        app: plog-user
    spec:
      containers:
        - name: plog-user
          image: skyish/plog-user:latest
          envFrom:
            - configMapRef:
                name: deployment-configmap
            - secretRef:
                name: deployment-secret
          ports:
            - containerPort: 5002

---
apiVersion: v1
kind: Service
metadata:
  name: plog-user-service
spec:
  selector:
    app: plog-user
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
