name: Build and Push Docker Images

on:
  push:
    paths:
      - 'Docker/**'

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Run Docker build script
        run: |
          chmod +x ./Docker/build.sh
          ./Docker/build.sh
